---
### Executable ###
- name: Get Caddy executable stats
  stat: path="{{ caddy_executable }}"
  register: caddy_stats

- name: Download Caddy
  get_url:
    url: "https://github.com/mholt/caddy/releases/download/v{{ caddy_version }}/caddy_v{{ caddy_version }}_linux_amd64.tar.gz"
    dest: /tmp
  when: caddy_stats.stat.exists == false

- name: Unarchive Caddy
  unarchive: src=/tmp/caddy_v{{ caddy_version }}_linux_amd64.tar.gz remote_src=yes dest=/tmp
  when: caddy_stats.stat.exists == false

- name: Caddy executable attributes
  file: path=/tmp/caddy_v{{ caddy_version }}_linux_amd64.tar.gz mode=0755
  when: caddy_stats.stat.exists == false

- name: Install Caddy
  command: mv /tmp/caddy "{{ caddy_executable }}"
  become: true
  when: caddy_stats.stat.exists == false

- name: Caddy setcap
  command: setcap CAP_NET_BIND_SERVICE=+eip "{{ caddy_executable }}"
  become: true
  # when: caddy_stats.stat.exists == false

- name: Create Caddy log directory
  file: path=/var/log/caddy state=directory mode=0755 owner="{{ caddy_user }}" group="{{ caddy_user }}" recurse=yes
  become: true

- name: Create Caddy SSL directory
  file: path=/etc/ssl/caddy state=directory mode=0755 owner="{{ caddy_user }}" group="{{ caddy_user }}" recurse=yes
  become: true

### Config ###
- name: Ensure /etc/caddy exists
  file: path=/etc/caddy state=directory mode=0755
  become: true

- name: Get Caddyfile stats
  stat: path="{{ caddyfile }}"
  register: caddyfile_stats

- name: Ensure Caddyfile exists
  file: path="{{ caddyfile }}" owner="{{ caddy_user }}" group="{{ caddy_user }}" state=touch
  become: true
  when: caddyfile_stats.stat.exists == false

### Service ###
- name: Copy systemd config file
  template: src=caddy.service.j2 dest=/etc/systemd/system/caddy.service owner=root group=root mode=0744
  become: true

- name: Enable Caddy service
  service: name=caddy enabled=yes
  become: true

- name: Start Caddy service
  systemd: name=caddy state=started daemon_reload=yes
  become: true

### SSH access ###
- name: Ensure users ssh directory exists
  file: path=/var/www/.ssh state=directory owner="{{ caddy_user }}" group="{{ caddy_user }}" mode=0700
  become: true
  when: ssh_access and caddy_user == 'www-data'

- name: Ensure users ssh directory exists
  file: path=/home/{{ caddy_user }}/.ssh state=directory owner="{{ caddy_user }}" group="{{ caddy_user }}" mode=0700
  become: true
  when: ssh_access and caddy_user != 'www-data'

- name: Ensure SFTP access
  authorized_key: user="{{ caddy_user }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  become: true
  when: ssh_access

- name: Caddy user login shell
  user: name="{{ caddy_user }}" shell=/bin/bash
  become: true
  when: ssh_access
